# Generated by Django 6.0 on 2026-01-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
