# Generated by Django 6.0 on 2026-03-26 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_alter_chatmessage_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='AssessmentRecord',
        ),
        migrations.RenameModel(
            old_name='ChatHistory',
            new_name='DailyAssessmentLog',
        ),
        migrations.RenameModel(
            old_name='Conversation',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='assessmentrecord',
            old_name='conversation',
            new_name='Patient',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkinCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('captured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captured_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
