# Generated by Django 6.0 on 2026-03-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_chatmessage_assessmentrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentrecord',
            old_name='Patient',
            new_name='patient',
        ),
    ]
