# Generated by Django 6.0 on 2026-03-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_patient_assessmentrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='General Practitioner', max_length=20),
        ),
    ]
