# Generated by Django 6.0 on 2026-05-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
